numero = int(input('Digite um número:'))
print('TABUADA DO NÚMERO {}' . format(numero))
#print('{} X  0 = {}' .format(numero, numero*0))
#print('{} X  1 = {}' .format(numero, numero*1))
#print('{} X  2 = {}' .format(numero, numero*2))
#print('{} X  3 = {}' .format(numero, numero*3))
#print('{} X  4 = {}' .format(numero, numero*4))
#print('{} X  5 = {}' .format(numero, numero*5))
#print('{} X  6 = {}' .format(numero, numero*6))
#print('{} X  7 = {}' .format(numero, numero*7))
#print('{} X  8 = {}' .format(numero, numero*8))
#print('{} X  9 = {}' .format(numero, numero*9))
#print('{} X 10 = {}' .format(numero, numero*10))

#RESULTADO MELHOR
print('-' * 12)# repetir '-' 12 vezes
print('{} x {:2} = {}' .format(numero, 1, numero*1))
print('{} x {:2} = {}' .format(numero, 2, numero*2))
print('{} x {:2} = {}' .format(numero, 3, numero*3))
print('{} x {:2} = {}' .format(numero, 4, numero*4))
print('{} x {:2} = {}' .format(numero, 5, numero*5))
print('{} x {:2} = {}' .format(numero, 6, numero*6))
print('{} x {:2} = {}' .format(numero, 7, numero*7))
print('{} x {:2} = {}' .format(numero, 8, numero*8))
print('{} x {:2} = {}' .format(numero, 9, numero*9))
print('{} x {:2} = {}' .format(numero, 10, numero*10))
print('-' * 12)
